import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { LoginButton } from "@/app/ui/auth/LoginButton";
import { User } from "@/app/ui/auth/User";
import { getAuthSession } from "@/lib/auth";
import './globals.css'
import Header from './ui/header/Header'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  
  const session = await getAuthSession()
  /*
  if (!session) {
    return {
      redirect: {
        destination: '/login',
        permanent: false,
      },
    }
  }
  */
  return (
    <html lang="en" className='h-full bg-gray-light'>
      <body className={inter.className}>
        <Header />
        {session ? (
            <div className='px-5'>
              {children}
            </div>
        ) : (
            <div></div>
        )}

      </body>
    </html>
  )
}
