import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Header from './ui/header/Header'
import { getAuthSession } from "@/lib/auth";

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const session = await getAuthSession()
  return (
    <html lang="en" className='h-full bg-gray-light'>
      <body className={`${inter.className} h-full`}>
        { session &&
          <Header />
        }
        <div>
          {children}
        </div>
      </body>
    </html>
  )
}
